In [4]:
import numpy as np
myarr = np.array([[5,4,6,8,78,75,7]])
myarr[0,1]

np.int64(4)

In [5]:
myarr.shape

(1, 7)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr [0,1] = 45
myarr

array([[ 5, 45,  6,  8, 78, 75,  7]])

In [8]:
list = np.array([[1,2,3],[2,3,5],[5,4,7]])
list

array([[1, 2, 3],
       [2, 3, 5],
       [5, 4, 7]])

In [9]:
list.size

9

In [10]:
list.shape

(3, 3)

In [11]:
list.dtype

dtype('int64')

In [12]:
a = np.zeros((3,3))

In [13]:
a


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.array({54,55})

array({54, 55}, dtype=object)

In [15]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
import pandas as pd

# Data
students = ['RAM', 'SHYAM', 'GITA', 'HARI', 'SITA', 'SUSHILA', 'RAMESH', 'SUBODH', 'ANIL', 'RUPA']
subjects = ['ENG', 'NEP', 'MAT', 'SCI', 'COM']
marks = [
    [57, 34, 93, 84, 54],
    [48, 49, 52, 89, 64],
    [66, 64, 75, 38, 84],
    [55, 47, 90, 82, 37],
    [45, 93, 70, 53, 76],
    [45, 63, 33, 53, 72],
    [68, 34, 42, 43, 84],
    [62, 69, 67, 50, 94],
    [59, 33, 51, 68, 33],
    [57, 91, 60, 37, 44]
]
indexing = [1,2,3,4,5,6,7,8,9,10]

# Create the DataFrame
df = pd.DataFrame({ "students" : students, 
                    "ENG" : [m[0] for m in marks],
                    "NEP" : [m[1] for m in marks],
                    "MAT" : [m[2] for m in marks],
                    "SCI" : [m[3] for m in marks],
                    "COM" : [m[4] for m in marks]
}, index = indexing)

# Display the DataFrame
df


students  ENG  NEP  MAT  SCI  COM
1       RAM   57   34   93   84   54
2     SHYAM   48   49   52   89   64
3      GITA   66   64   75   38   84
4      HARI   55   47   90   82   37
5      SITA   45   93   70   53   76
6   SUSHILA   45   63   33   53   72
7    RAMESH   68   34   42   43   84
8    SUBODH   62   69   67   50   94
9      ANIL   59   33   51   68   33
10     RUPA   57   91   60   37   44

Fetch the records of all the students who have passed in Nepali. 

In [17]:
serial_no = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
subjects = ['ENG', 'NEP', 'MAT', 'SCI', 'COM']
students = ['RAM','SHYAM','GITA','HARI','SITA','SUSHILA','RAMESH','SUBODH','ANIL','RUPA']
marks = [
    [57, 34, 93, 84, 54], 
    [48, 49, 52, 89, 64], 
    [66, 64, 75, 38, 84], 
    [55, 47, 90, 82, 37], 
    [45, 93, 70, 53, 76], 
    [45, 63, 33, 53, 72], 
    [68, 34, 42, 43, 84], 
    [62, 69, 67, 50, 94], 
    [59, 33, 51, 68, 33], 
    [57, 91, 60, 37, 44]
]
df_ = pd.DataFrame(marks, columns=subjects, index=students)

# Displaying the DataFrame
print(df_)

         ENG  NEP  MAT  SCI  COM
RAM       57   34   93   84   54
SHYAM     48   49   52   89   64
GITA      66   64   75   38   84
HARI      55   47   90   82   37
SITA      45   93   70   53   76
SUSHILA   45   63   33   53   72
RAMESH    68   34   42   43   84
SUBODH    62   69   67   50   94
ANIL      59   33   51   68   33
RUPA      57   91   60   37   44


In [20]:
marks = np.array([
    [57, 34, 93, 84, 54],
    [48, 49, 52, 89, 64],
    [66, 64, 75, 38, 84],
    [55, 47, 90, 82, 37],
    [45, 93, 70, 53, 76],
    [45, 63, 33, 53, 72],
    [68, 34, 42, 43, 84],
    [62, 69, 67, 50, 94],
    [59, 33, 51, 68, 33],
    [57, 91, 60, 37, 44]
])
marks.shape

(10, 5)